### ISSUE TITLE
Peer Review - Gina Zheng

### ISSUE THREAD

**Issue by gina622** [KentPendergast/PenVest#2]
Hi Kent,

I really like the different effects you have with the word invest and the content below that. 

One thing I found in your record page is that you put two class attributes for one of the images in lines 67 and 68. Another thing is on your contact page, the for attribute of the labels should refer to a specific id of an input. For example the label in line 229, instead of for = "html" i think it should be 'retirement'.

For the content, I was a bit confused as to what the function was for the two red buttons on the left side until I clicked on them. I think a little text that explains it would be nice. On the impact page, for the table that shows the goals, adjusting the table and images to get the full view would be nice.

**Comment by KentPendergast** [comment]
Thank you very much for your feedback! I will definitely take these into consideration.
