### ISSUE TITLE
Peer Review - Ysbely Santos 

### ISSUE THREAD

**Issue by Ysbely** [KentPendergast/PenVest#3]
Hey Kent,
I really loved the site, it was super creative. 

That being said, in terms of editing I think the site would be better if you were to add some padding to the text boxes. On some of the pages, there are images or something above the text, but adding padding can help that. Some of the boxes at the bottom are cut off, it should be a bigger Box. Add a padding-right so that it does not look like the pages are not centered. Finally, I think you should also link the HTML files to their corresponding header tab.

Best,
Ysbely Santos

**Comment by KentPendergast** [comment]
Ysbely, Thank you for the feedback! I will add more padding and work on the spacing of my site.
